# Generated by Django 5.2.5 on 2025-08-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_lesson_course"),
        ("users", "0002_alter_pay_options_alter_pay_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pay",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="pay",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="lms.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
