# Generated by Django 5.2.5 on 2025-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscribeuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pay",
            name="link",
            field=models.TextField(blank=True, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="pay",
            name="session_id",
            field=models.TextField(blank=True, null=True, verbose_name="ИД сессии"),
        ),
    ]
