# Generated by Django 5.2.5 on 2025-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="lesson/", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.TextField(blank=True, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
